version: '3.9'

services:
  mysql-db:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - two-tier
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 20s

  django-app:
    build: .
    container_name: django_count
    command: sh -c "python manage.py migrate --no-input && gunicorn notesapp.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    networks:
      - two-tier
    restart: always
    depends_on:
      mysql-db:
        condition: service_healthy
    env_file:
      - ".env"
    healthcheck:
      test: ["CMD-SHELL","curl -f http://localhost:8000/admin || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 20s

  nginx-server:
    build:
      context: ./nginx
    container_name: nginx_count
    ports:
      - "80:80"
    networks:
      - two-tier
    restart: always
    depends_on:
      - django-app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf


volumes:
  mysql-data:

networks:
  two-tier:
